name: Signal Node - Sei - Uniswap

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build Tool
      run: |
        make build
    - name: Build Chain
      run: |
        git clone -b v5.9.0-hotfix https://github.com/sei-protocol/sei-chain.git
        cd sei-chain
        make build-docker-node &> build.log
        make run-local-node &> chain.log &
        sleep 120
        echo 'chain.log'
        tail chain.log
        container_id=$(docker ps -q | head -n 1)
        docker exec $container_id sh -c 'echo "12345678" | ./build/seid tx evm send 0x20f33CE90A13a4b5E7697E3544c3083B8F8A51D4 100000000000000 --from node_admin'
        sleep 5
        docker exec $container_id sh -c 'echo "12345678" | ./build/seid tx evm associate-address fffdbb37105441e14b0ee6330d855d8504ff39e705c3afa8f859ac9865f99306 --from node_admin'
        sleep 5
        docker exec $container_id sh -c 'echo "12345678" | ./build/seid tx bank send node_admin sei1667q4rnlspl4luk4s6mupl99w4sgglsh57am2l 1000000000000usei -y --fees 2000usei'
        sleep 5
        cd ../../evmchainbench
        ./bin/evmchainbench run --tx-count 20000 --mempool 1000 -s 2 -p uniswap
