name: Signal Node - Evmos

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Build Tool
      run: |
        make build
    - name: Build Chain
      run: |
        git clone -b v20.0.0 https://github.com/evmos/evmos.git
        cd evmos
        make install
        ./local_node.sh > chain.log 2>&1 &
        while ! nc -z localhost 8546; do sleep 1; done
        cd ../../evmchainbench
        ./bin/evmchainbench run --faucet-private-key 8A36C69D940A92FCEA94B36D0F2928C7A0EE19A90073EDA769693298DFA9603B --tx-count 20000 --mempool 2500
